name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --html=reports/report.html
      continue-on-error: true

    - name: Upload test report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: reports/report.html
