name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [test, staging]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --env ${{ matrix.env }}
      continue-on-error: true

    - name: Upload test report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: reports/report.html
